
spring: 
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: '@project.artifactId@'
    
custom:
  project:
    basepackage: '@custom.project.basepackage@'
    

ggx:
  core: 
    port: 10001
    websocketPath: /websocket
    change-and-reboot-if-port-in-use: true
    workThreadSize: 4
    ping-pong-enabled: true
  registry:
    client:
      service-name: '@project.artifactId@'
      service-group-id: '@service.group.id@'
      registries:
        - domain: '@registry.server.domain@'
          port: '@registry.server.port@'


logging:
  file: '/app/logs/@project.artifactId@/@project.artifactId@.log'
  level: 
    root: info
    
 
