
spring: 
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: '@project.artifactId@'
    
custom:
  project:
    basepackage: '@custom.project.basepackage@'
    

ggx:
  core: 
    port: 10001
    websocketPath: /websocket
    change-and-reboot-if-port-in-use: true
    port-change-strategy: increment
  router:
    client:
      router-group-id: '@gateway.router.group.id@'
      session-disconnect-transfer-request-enabled: true
      session-disconnect-transfer-response-enabled: false
  registry:
    client:
      service-name: '@project.artifactId@'
      registries:
        - domain: '@registry.server.domain@'
          port: '@registry.server.port@'


logging:
  file: '/app/logs/@project.artifactId@/@project.artifactId@.log'
  level: 
    root: info
    io:
      netty: info
    
 
