

ggx: 
  enabled: true
  mode: EVENTBUS_CLIENT
  registry:
    client:
      service-name: '@project.artifactId@'
      registries:
        - domain: '@registry.server.domain@'
          port: '@registry.server.port@'
  router: 
    server: 
      action-id-prefix: '@game.action.id.prefix@'
      router-group-id: '@game.group@'
      boot-with-random-port: true
      change-and-reboot-if-port-in-use: true
      port-change-strategy: 'random'
      session-disconnect-transfer-request-enabled: true
      session-disconnect-transfer-response-enabled: true